version: "3"
services:
  db:
    container_name: db
    build: ./db 
    environment:
      - MYSQL_ROOT_PASSWORD=pwd123
      - MYSQL_DATABASE=elearning
      - MYSQL_USER=root
  flask:
    container_name: flask_app
    build: ./app
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=4000
      - MYSQL_ROOT_PASSWORD=pwd123
      - MYSQL_DATABASE=elearning
      - MYSQL_USER=root
      - MYSQL_HOST=db
    ports: 
      - "3000:4000"
    restart: always
    depends_on:
      - db
    command: ./wait-for-it.sh db:3306 -- python3 app.py
