version: "3"
services:
  flask:
    container_name: flask_app
    build: ./app
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=4000
    ports: 
      - "3000:4000"
    restart: always
    command: python3 app.py
